openapi: 3.0.0
info:
  title: Swagger Bay
  version: 1.0.0
servers:
  - url: http://demoapi.apifortress.com
tags:
- name: demo
  description: Call to API Fortress demo API for demo purposes
paths:
  /api/retail/product:
    get:
      tags:
        - default
      summary: Demo API - APIF
      parameters:
        - name: key
          in: header
          schema:
            type: string
          example: ABC123
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}

